/******************************************************************************
 *
 * Module: Ultrasonic driver.
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ultrasonic driver.
 *
 * Author: Malek Mahmoud Mohammmed
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include <avr/io.h> /* To set the pins directions */
#include "icu.h" /* to use ICU functions */
#include "gpio.h"
#include "avr/delay.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
Icu_ConfigType g_icuConfig = {F_CPU_8,RISING};
uint16 g_pulsetime=0;
uint8 g_edgeCount =0;
/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Function to initialize the ultrasoinc driver.
 * 	1. call initialzation function of ICU driver.
 * 	2. setup the ICU call back function.
 * 	3. setup the direction of the tigger pin as output pin through the
 * 	   GPIO driver.
 */
void ultrasonic_init(void)
{
	Icu_init(&g_icuConfig); /*passing the configration structure by address to ICU init function*/
	Icu_setCallBack(ultrasonic_edgeProcessing); /*passing the call back dunction to the ICU driver*/
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT); /**setting the direction of the trigger pin as output pin*/
}
/*
 * Description: Function to send the trigger pulse.
 */
void ultrasonic_trigger(void)
{
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description: Function to send the trigger pulse using ultrasonic_trigger function.
 * 				Start the measurements by the ICU from this moment.
 * 				Return the measured distance in Centimeter.
 */
uint16 ultrasonic_readDistance(void)
{
	static uint16 l_distance = 0;
	ultrasonic_trigger();
	if(g_edgeCount == 2)
	{
		g_edgeCount =0;
		l_distance = (uint16)(((g_pulsetime)*((uint32)SOUND_VELOCITY*FREQ_PRESCALER)/(F_CPU*2)));
	}
	return l_distance;
}

/*
 * Description: The call back function that called by ICU driver.
 *              the function is used to calculate the high time generated by
 *              the ulrasonic sensor.
 *
 */
void ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_pulsetime = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
	}
	else
	{
		/* nothing doing*/
	}
}
