 /******************************************************************************
 *
 * Module: Ultrasonic driver.
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the AVR ultrasonic driver.
 *
 * Author: Malek Mahmoud Mohammmed
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define TRIGGER_PORT_ID PORTB_ID
#define TRIGGER_PIN_ID  PIN5_ID
#define SOUND_VELOCITY 34000
/*******************************************************************************
 *                            Functions Prototypes                             *
 *******************************************************************************/
/*
 * Description : Function to initialize the ultrasoinc driver.
 * 	1. call initialzation function of ICU driver.
 * 	2. setup the ICU call back function.
 * 	3. setup the direction of the tigger pin as output pin through the
 * 	   GPIO driver.
 */
void ultrasonic_init(void);
/*
 * Description: Function to send the trigger pulse.
 */
void ultrasonic_trigger(void);

/*
 * Description: Function to send the trigger pulse using ultrasonic_trigger function.
 * 				Start the measuremnts by the ICU from this moment.
 * 				Return the measured distance in Centimeter.
 */
uint16 ultrasonic_readDistance(void);

/*
 * Description: The call back function that called by ICU driver.
 *              the function is used to calculate the high time generated by
 *              the ulrasonic sensor.
 *
 */
void ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
